---
name: test and build
on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sdk: 'src/**'
            dapp: 'dapp/**'
            www: 'www/**'
            sanity: 'packages/sanity-plugin-kubelt/**'
            ext: 'ext/**'


  build-ddt:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run build:ddt:develop

  build-kbt:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run build:kbt:develop

  build-p2p:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run build:p2p:develop

  build-sdk:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run build:sdk:develop

  build-sdk-web:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run build:sdk-web:develop

  test-sdk-cljs:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run test:sdk:cljs:develop

  test-sdk-js:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run test:sdk:js:develop

  test-web:
    if: steps.changes.outputs.sdk == 'true'
    runs-on: ubuntu-latest
    env:
      CHROME_BIN: /snap/bin/chromium
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev chromium-browser
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
        # Run the CI version of the web tests using headless Chrome.
      - run: npm run test:web:ci

  # test-sdk-web:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #         cache: 'npm'
  #         cache-dependency-path: package-lock.json
  #     - run: sudo apt-get install -y libsystemd-dev
  #     - run: npm install
  #     - uses: turtlequeue/setup-babashka@v1.3.0
  #       with:
  #         babashka-version: 0.7.8
  #     - run: npm run test:sdk-web:develop

  test-dapp:
    if: steps.changes.outputs.dapp == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run test:dapp:develop

  test-plugin-sanity:
    if: steps.changes.outputs.sanity == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run test:plugin:sanity
