---
name: test and build
on:
  pull_request:
    branches:
      - main

jobs:
  ddt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run build:ddt:develop
  kbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.8
      - run: npm run build:kbt:develop
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Source Builds
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.4
      - run: npm run test:all:develop
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: 1.11.0.1097
          #lein: latest
          #boot: latest
      - name: build literate docs
        run: clojure -M:docs
        shell: bash
