---
name: test and build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  # Test
  #-----------------------------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Source Builds
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - run: npm run test:all:develop
