---
name: test and build
on:
  push:
    branches:
      - main

jobs:

  # build
  # ----------------------------------------------------------------------------

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    services:
      cloudflare-worker:
        image: ghcr.io/kubelt/cloudflare-worker:latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
        ports:
          - 8787:8787
    steps:
      - uses: actions/checkout@master
      - uses: DeLaGuardo/setup-clojure@8.0
        with:
          bb: 0.8.156
          cli: 1.11.1.1149
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm ci
      # - run: npm install cypress --save-dev
      - run: npm run test:all:release

  # three-id
  # ----------------------------------------------------------------------------

  three-id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - uses: DeLaGuardo/setup-clojure@8.0
        with:
          bb: 0.8.156
          cli: 1.11.1.1149

      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: install node dependencies
        run: npm ci

      - name: build sdk-web
        run: npm run build:sdk-web:release

      - name: install node dependencies (for three-id)
        working-directory: ./three-id
        run: npm ci

      - name: build and deploy three-id
        working-directory: ./three-id
        env:
          # These values are injected into the generated wrangler.toml.
          ADMIN_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          NEXT_KV_APP_ID: ${{ secrets.NEXT_KV_APP_ID }}
          CURRENT_KV_APP_ID: ${{ secrets.CURRENT_KV_APP_ID }}
          # The Datadog client token.
          DATADOG_TOKEN: ${{ secrets.DATADOG_TOKEN }}
          # The Cloudflare API token used by wrangler.
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: bb deploy:app --deploy-env next
