---
name: test and build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Source Builds
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - name: Setup & Run Build
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.4
      - run: npm run test:all:release
      # TODO: Do we want to replease a @kubelt/package@prerelease to github registry or npm?
      #- name: Publish Next
        #run: npx lerna publish --canary --preid next --yes
