---
name: test and build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    services:
      cloudflare-worker:
        image: ghcr.io/kubelt/cloudflare-worker:latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
        ports:
          - 8787:8787
    steps:
      - uses: actions/checkout@master
      - uses: DeLaGuardo/setup-clojure@5.1
        with:
          bb: 0.8.156
          cli: 1.11.1.1113
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm install cypress --save-dev
      - run: npm run test:all:release
      # TODO: Do we want to replease a @kubelt/package@prerelease to github registry or npm?
      #- name: Publish Next
        #run: npx lerna publish --canary --preid next --yes
