---
name: test and build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    services:
      cloudflare-worker:
        image: ghcr.io/kubelt/cloudflare-worker:latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
        ports:
          - 8787:8787
    steps:
      - uses: actions/checkout@master
      - uses: DeLaGuardo/setup-clojure@7.0
        with:
          bb: 0.8.156
          cli: 1.11.1.1149
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm install cypress --save-dev
      - run: npm run test:all:release

      # - name: [three-id] generate wrangler.toml for CloudFlare
      #   env:
      #     ADMIN_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
      #     NEXT_KV_GATE_ID: ${{ secrets.NEXT_KV_GATE_ID }}
      #     NEXT_KV_SITE_ID: ${{ secrets.NEXT_KV_SITE_ID }}
      #   working-directory: ./three-id
      #   run: bb wrangler:toml

      # - name: [three-id] run preflight checks
      #   working-directory: ./three-id
      #   run: bb check:all

      # - name: [three-id] wrangler login
      #   working-directory: ./three-id
      #   run: xxx

      # - name: [three-id] deploy the application
      #   working-directory: ./three-id
      #   run: bb deploy:app --deploy-env next

      # TODO: Do we want to replease a @kubelt/package@prerelease to github registry or npm?
      #- name: Publish Next
        #run: npx lerna publish --canary --preid next --yes
