---
name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      sdk: ${{ steps.changes.outputs.sdk }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sdk: 'src/**'
  literate:
    needs: changes
    if: needs.changes.outputs.sdk == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: 1.11.1.1149
          #lein: latest
          #boot: latest
          #bb: latest
      - name: build literate docs
        run: clojure -M:sidenotes
        shell: bash
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: sdk.kubelt.com
