---
name: release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & Test
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: sudo apt-get install -y libsystemd-dev
      - run: npm install
      - name: Setup & Run Build
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.4
      - run: npm run test:all:release
      - name: Get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release
        run: npx lerna version ${{ env.RELEASE_VERSION }} 
      - name: Publish
        run: npx lerna publish
